export type AppStatus = 'active' | 'beta' | 'coming_soon'

export interface AppDef {
  id: string
  name: string
  description: string
  icon: string
  color: string
  bgColor: string
  url: string
  status: AppStatus
  category: string
  badge?: string
  /** If true, only users with role 'admin' or 'superadmin' see this card. */
  adminOnly?: boolean
  /** If true, treat url as an internal Hub path (skip /api/auth/launch). */
  internal?: boolean
}

export const APPS: AppDef[] = [
  {
    id: 'clinicpnl',
    name: 'ClinicPNL',
    description: 'Dashboard financiero con rentabilidad, EBITDA y KPIs por clínica.',
    icon: 'Activity',
    color: '#003A70',
    bgColor: '#e6eef7',
    url: process.env.NEXT_PUBLIC_URL_CLINICPNL || '#',
    status: 'active',
    category: 'Financiero',
  },
  {
    id: 'clinicvox',
    name: 'ClinicVox',
    description: 'Automatización de llamadas y confirmación de citas por voz.',
    icon: 'Phone',
    color: '#00A99D',
    bgColor: '#e0f7f6',
    url: process.env.NEXT_PUBLIC_URL_CLINICVOX || '#',
    status: 'active',
    category: 'Comunicación',
  },
  {
    id: 'dentalhr',
    name: 'DentalHR',
    description: 'Gestión de recursos humanos para clínicas dentales.',
    icon: 'UserCheck',
    color: '#059669',
    bgColor: '#d1fae5',
    url: process.env.NEXT_PUBLIC_URL_DENTALHR || '#',
    status: 'active',
    category: 'RRHH',
  },
  {
    id: 'fichaje',
    name: 'Fichajeshr',
    description: 'Control horario con geolocalización, kiosko y app móvil.',
    icon: 'Clock',
    color: '#16a34a',
    bgColor: '#dcfce7',
    url: process.env.NEXT_PUBLIC_URL_FICHAJE || '#',
    status: 'active',
    category: 'RRHH',
  },
  {
    id: 'spendflow',
    name: 'SpendFlow',
    description: 'Gastos corporativos, kilometraje y reembolsos tipo SAP Concur.',
    icon: 'Receipt',
    color: '#d97706',
    bgColor: '#fef3c7',
    url: process.env.NEXT_PUBLIC_URL_SPENDFLOW || '#',
    status: 'active',
    category: 'Gastos',
  },
  {
    id: 'zentrix',
    name: 'ZENTRIX',
    description: 'ERP cloud completo: facturación, contabilidad, CRM y RRHH.',
    icon: 'LayoutGrid',
    color: '#7c3aed',
    bgColor: '#ede9fe',
    url: process.env.NEXT_PUBLIC_URL_ZENTRIX || '#',
    status: 'active',
    category: 'ERP',
  },
  {
    id: 'clinicrefunds',
    name: 'ClinicRefunds',
    description: 'Gestión de devoluciones y reembolsos para pacientes dentales.',
    icon: 'RefreshCcw',
    color: '#003A70',
    bgColor: '#e6eef7',
    url: process.env.NEXT_PUBLIC_URL_CLINICREFUNDS || '#',
    status: 'active',
    category: 'Financiero',
  },
  {
    id: 'clinicstock',
    name: 'ClinicStock',
    description: 'Gestión de stock dental, compras, inventarios y movimientos para clínicas multicentro.',
    icon: 'Package',
    color: '#003A70',
    bgColor: '#e6eef7',
    url: process.env.NEXT_PUBLIC_URL_CLINICSTOCK || 'https://clinicstock.vercel.app',
    status: 'active',
    category: 'Clínica',
  },
  {
    id: 'dentalreports',
    name: 'DentalReports',
    description: 'Informes avanzados, comparativas y analítica para clínicas.',
    icon: 'BarChart3',
    color: '#0891b2',
    bgColor: '#cffafe',
    url: process.env.NEXT_PUBLIC_URL_DENTALREPORTS || '#',
    status: 'active',
    category: 'Financiero',
  },
  {
    id: 'nexora',
    name: 'Nexora',
    description: 'Comunicación interna corporativa: chat, anuncios, documentos y tablón para grupos de clínicas.',
    icon: 'MessageSquare',
    color: '#7c3aed',
    bgColor: '#ede9fe',
    url: process.env.NEXT_PUBLIC_URL_NEXORA || '#',
    status: 'active',
    category: 'Comunicación',
  },
  {
    id: 'impulsodent-crm',
    name: 'Impulsodent CRM',
    description: 'CRM de leads con tablero Monday-like, WhatsApp Business integrado y automatizaciones.',
    icon: 'Target',
    color: '#003A70',
    bgColor: '#e6eef7',
    url: process.env.NEXT_PUBLIC_URL_IMPULSODENT_CRM || 'https://crm.impulsodent.com',
    status: 'active',
    category: 'CRM',
  },
  {
    id: 'talent',
    name: 'Impulsodent Talent',
    description: 'Evaluación del desempeño, matriz 9-box y planes de desarrollo para tu equipo dental.',
    icon: 'Grid3x3',
    color: '#003A70',
    bgColor: '#e6eef7',
    url: process.env.NEXT_PUBLIC_URL_TALENT || 'https://talent.impulsodent.com',
    status: 'active',
    category: 'RRHH',
  },
  {
    id: 'clinicnps',
    name: 'ImpulsoNPS',
    description: 'Encuestas NPS automatizadas por WhatsApp y email para medir la satisfacción de pacientes dentales.',
    icon: 'Star',
    color: '#003A70',
    bgColor: '#e6eef7',
    url: process.env.NEXT_PUBLIC_URL_CLINICNPS || 'https://clinicnps-seven.vercel.app',
    status: 'active',
    category: 'Pacientes',
  },
  {
    id: 'clinicleads',
    name: 'ClinicLeads',
    description: 'Captación y gestión de leads para clínicas.',
    icon: 'Target',
    color: '#0D9488',
    bgColor: '#ccfbf1',
    url: process.env.NEXT_PUBLIC_URL_CLINICLEADS || 'https://clinicleads.impulsodent.com',
    status: 'active',
    category: 'CRM',
  },
  {
    id: 'duediligence',
    name: 'Due Diligence',
    description: 'Due diligence dental: EBITDA normalizado, valoración M&A, scoring 0-100, red flags y simulador de negociación.',
    icon: 'ScanSearch',
    color: '#0D9488',
    bgColor: '#ccfbf1',
    url: process.env.NEXT_PUBLIC_URL_DUEDILIGENCE || 'https://due.impulsodent.com',
    status: 'active',
    category: 'Financiero',
    badge: 'Nuevo',
  },
  {
    id: 'ddc',
    name: 'DDC · Adquisiciones',
    description: 'Due diligence operativa para adquisición o reapertura de redes dentales: 11 secciones (sanitario, legal, RRHH, RGPD), checklists, score 0-100 e informe ejecutivo.',
    icon: 'ClipboardCheck',
    color: '#143b63',
    bgColor: '#eff6ff',
    url: process.env.NEXT_PUBLIC_URL_DDC || 'https://ddc.impulsodent.com',
    status: 'active',
    category: 'Financiero',
    badge: 'Nuevo',
    internal: true,
  },
  {
    id: 'historiales',
    name: 'Historiales Clínicos',
    description: 'Solicitud, validación y entrega de historiales clínicos con trazabilidad completa, workflow multinivel y cumplimiento RGPD.',
    icon: 'FolderOpen',
    color: '#003A70',
    bgColor: '#e6eef7',
    url: process.env.NEXT_PUBLIC_URL_HISTORIALES || 'https://historiales.impulsodent.com',
    status: 'active',
    category: 'Clínica',
    badge: 'Nuevo',
  },
  {
    id: 'casos-clinicos',
    name: 'Resolución de Casos Clínicos',
    description: 'Solicitud, revisión y resolución médica de casos clínicos dentales por especialidad, con versionado y auditoría completa.',
    icon: 'Stethoscope',
    color: '#003A70',
    bgColor: '#e6eef7',
    url: process.env.NEXT_PUBLIC_URL_CASOSCLINICOS || 'https://casos-clinicos.impulsodent.com',
    status: 'active',
    category: 'Clínica',
    badge: 'Nuevo',
  },
  {
    id: 'helpdesk',
    name: 'Helpdesk',
    description: 'Helpdesk multi-categoría (mantenimiento, IT, RRHH, administración) con SLA, grupos de soporte, KB y reportes.',
    icon: 'LifeBuoy',
    color: '#003A70',
    bgColor: '#e6eef7',
    url: process.env.NEXT_PUBLIC_URL_HELPDESK || 'https://helpdesk.impulsodent.com',
    status: 'active',
    category: 'Administración',
    badge: 'Nuevo',
  },
  {
    id: 'pedistock',
    name: 'Pedidos & Inventario',
    description: 'Centralización de proveedores, pedidos, recepción de mercancía y control de stock con aprobación superior a 200 €.',
    icon: 'Package',
    color: '#00A99D',
    bgColor: '#e0f7f6',
    url: process.env.NEXT_PUBLIC_URL_PEDISTOCK || 'https://pedistock.impulsodent.com',
    status: 'active',
    category: 'Operaciones',
    badge: 'Nuevo',
  },
  {
    id: 'margincall',
    name: 'MarginCall',
    description: 'Calculadora de margen por tratamiento: especialidades, actos, honorarios y rentabilidad para clínicas dentales.',
    icon: 'Calculator',
    color: '#0D9488',
    bgColor: '#ccfbf1',
    url: process.env.NEXT_PUBLIC_URL_MARGINCALL || 'https://margincall.impulsodent.com',
    status: 'active',
    category: 'Financiero',
    badge: 'Nuevo',
  },
  {
    id: 'competidor',
    name: 'Competidor Radar',
    description: 'Analiza competencia dental por zona, precios, reputación y posicionamiento.',
    icon: 'Radar',
    color: '#003A70',
    bgColor: '#e6eef7',
    url: process.env.NEXT_PUBLIC_URL_COMPETIDOR || 'https://competidor.impulsodent.com',
    status: 'active',
    category: 'Estratégico',
    badge: 'Nuevo',
  },
  {
    id: 'leadsreport',
    name: 'LeadsReport',
    description: 'Captura mensual de leads por clínica, comparativa entre centros, evolución histórica y export PDF ejecutivo.',
    icon: 'TrendingUp',
    color: '#0d9488',
    bgColor: '#ccfbf1',
    url: process.env.NEXT_PUBLIC_URL_LEADSREPORT || 'https://leadsreports.impulsodent.com',
    status: 'active',
    category: 'CRM',
    badge: 'Nuevo',
  },
  {
    id: 'sync-adapter',
    name: 'Sync Adapter',
    description: 'Capa master de datos clínicos: sincronización Gesden→Cloud para pacientes y citas. Solo admins.',
    icon: 'RefreshCw',
    color: '#003A70',
    bgColor: '#e6eef7',
    url: process.env.NEXT_PUBLIC_URL_SYNC_ADAPTER || 'https://syncadapter.impulsodent.com',
    status: 'active',
    category: 'Administración',
    adminOnly: true,
  },
  {
    id: 'integrations',
    name: 'Integraciones',
    description: 'Gestiona conectores, claves API y sincronización entre Hub y sub-aplicativos. Sólo administradores.',
    icon: 'Plug',
    color: '#0d9488',
    bgColor: '#ccfbf1',
    url: '/admin/integrations',
    status: 'active',
    category: 'Administración',
    adminOnly: true,
    internal: true,
  },
]

export const CATEGORIES = ['Todos', ...Array.from(new Set(APPS.map((a) => a.category)))]
